#!/usr/bin/perl

use strict;

my $word_count = 0;
while (my $line=<STDIN>) {
  chomp $line;
  next if $line =~ m/^[>#]/;
  while ($line=~m/([\w"'][^\s\-]+)/g) {
    ++$word_count;
  }
}
print "$word_count words\n";

